apiVersion: v1
data:
  eg-primary.yaml: |
    cluster-name: easegress-ingress-controller
    cluster-role: primary
    cluster:
      listen-client-urls:
      - http://0.0.0.0:2379
      listen-peer-urls:
      - http://0.0.0.0:2380
      initial-cluster:
      {{- $releasename := printf "%s" .Release.Name -}}
      {{- range $i, $e := until (.Values.cluster.replicas | int) }}
      - {{ $releasename }}-{{$i}}: http://{{ $releasename }}-{{$i}}.easegress-hs.default:2380
      {{- end }}
    api-addr: 0.0.0.0:2381
    data-dir: /opt/eg-data/data
    wal-dir: ""
    cpu-profile-file: ""
    memory-profile-file: ""
    log-dir: /opt/eg-data/log
    debug: false
  controller.yaml: |
    kind: IngressController
    name: {{ .Values.controller.name }}
    {{- if .Values.controller.namespaces }}
    namespaces:
    {{- range .Values.controller.namespaces }}
    - {{ . }}
    {{- end }}
    {{- end }}
    ingressClass: {{ .Values.ingressClass.name }}
    httpServer:
      port: 8080
      https: false
      keepAlive: true
      keepAliveTimeout: 60s
      maxConnections: 10240
  eg-secondary.yaml: |
    cluster-name: easegress-ingress-controller
    cluster-role: secondary
    cluster:
      primary-listen-peer-urls:
      - http://{{ .Release.Name }}-0.easegress-hs.default:2380
    api-addr: 0.0.0.0:2381
    data-dir: /opt/eg-data/data
    wal-dir: ""
    cpu-profile-file: ""
    memory-profile-file: ""
    log-dir: /opt/eg-data/log
    debug: false
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
