kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: 8080
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
