name: writer-001
labels:
  alive-probe:  http://127.0.0.1:12381/apis/v1
  application-port: 12381 
  mesh-servicename: mesh-app-frontend
  mesh-role: worker
cluster-name: cluster-test
cluster-role: writer
cluster-listen-client-urls: [http://127.0.0.1:12379]
cluster-listen-peer-urls: [http://127.0.0.1:12380]
cluster-advertise-client-urls: [http://127.0.0.1:12379]
cluster-initial-advertise-peer-urls: [http://127.0.0.1:12380]
cluster-join-urls: [http://127.0.0.1:12380, http://127.0.0.1:22380, http://127.0.0.1:32380]
api-addr: 127.0.0.1:12381
data-dir: ./data
wal-dir: ""
cpu-profile-file:
memory-profile-file:
log-dir: ./log
member-dir: ./member
std-log-level: INFO
