kind: MeshController
name: easemesh-controller
apiPort: 13009
ingressPort: 19527
externalServiceRegistry:
cleanExternalRegistry: true
heartbeatInterval: 5s
registryType: consul
#security:
#  mtlsMode: strict
#  certProvider: selfSign
#  rootCertTTL: 20h
#  appCertTTL: 10h
