name: primary-003
cluster-name: cluster-test
cluster-role: primary
cluster:
  listen-peer-urls:
   - http://127.0.0.1:32380
  listen-client-urls:
   - http://127.0.0.1:32379
  advertise-client-urls:
   - http://127.0.0.1:32379
  initial-advertise-peer-urls:
   - http://127.0.0.1:32380
  initial-cluster:
   - primary-001: http://127.0.0.1:12380
   - primary-002: http://127.0.0.1:22380
   - primary-003: http://127.0.0.1:32380
api-addr: 127.0.0.1:32381
data-dir: ./data
wal-dir: ""
cpu-profile-file:
memory-profile-file:
log-dir: ./log
member-dir: ./member
debug: false
