name: reader-005
cluster-name: cluster-test
cluster-role: reader
cluster-listen-client-urls:
cluster-listen-peer-urls:
cluster-advertise-client-urls:
cluster-initial-advertise-peer-urls:
cluster-join-urls: [http://127.0.0.1:12380, http://127.0.0.1:22380, http://127.0.0.1:32380]
api-addr: 127.0.0.1:52381
data-dir: ./data
wal-dir: ""
cpu-profile-file:
memory-profile-file:
log-dir: ./log
member-dir: ./member
debug: false
