name: writer-2
cluster-name: cluster-test
cluster-role: writer
api-addr: localhost:2381
data-dir: ./data
wal-dir: ""
cpu-profile-file:
memory-profile-file:
log-dir: ./log
debug: false
cluster:
  listen-peer-urls:
   - http://127.0.0.1:2378
  listen-client-urls:
   - http://127.0.0.1:2377
  advertise-client-urls:
   - http://127.0.0.1:2377
  initial-advertise-peer-urls:
   - http://127.0.0.1:2378
  initial-cluster:
   - writer-1: http://127.0.0.1:2380
   - writer-2: http://127.0.0.1:2378
   - writer-3: http://127.0.0.1:2376
