{{- if not .Values.cluster.useStandaloneEtcd }}
apiVersion: v1
kind: Service
metadata:
  name: easegress-hs
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: admin-port
    port: 2381
    protocol: TCP
    targetPort: 2381
  - name: peer-port
    port: 2380
    protocol: TCP
    targetPort: 2380
  - name: client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP

---

{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: easegress-public
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: admin-port
    port: 2381
    protocol: TCP
    targetPort: 2381
    nodePort: {{ .Values.service.adminPort }}
  selector:
    app: {{ .Release.Name }}
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: 8080
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
