/*
 * Copyright (c) 2017, MegaEase
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package generate generates codes for egbuilder.
package generate

import (
	"strings"

	j "github.com/dave/jennifer/jen"
	"github.com/megaease/easegress/v2/cmd/builder/utils"
)

func CreateRegistry(config *ObjectConfig) *j.File {
	file := j.NewFile("registry")
	file.HeaderComment("Code generated by egbuilder. DO NOT EDIT.\n")
	file.Comment("import " + egLogger).Line()
	file.ImportName(egFilters, "filters")
	file.ImportName(egSupervisor, "supervisor")
	file.ImportName(egAPI, "api")

	for _, f := range config.Filters {
		file.ImportName(utils.GetFilterPath(config.Repo, f), strings.ToLower(f))
	}
	for _, r := range config.Resources {
		file.ImportName(utils.GetResourcePath(config.Repo, r), strings.ToLower(r))
	}

	defineRegisterInit(file, config)
	return file
}

func defineRegisterInit(file *j.File, config *ObjectConfig) {
	codes := []j.Code{}

	appendCode := func(code j.Code) {
		codes = append(codes, code)
	}

	for _, f := range config.Filters {
		path := utils.GetFilterPath(config.Repo, f)
		appendCode(j.Comment("register filter " + f))
		appendCode(j.Qual(egFilters, "Register").Call(j.Qual(path, KindName)))
		appendCode(j.Line())
	}
	for _, r := range config.Resources {
		path := utils.GetResourcePath(config.Repo, r)
		appendCode(j.Comment("register resource " + r))
		appendCode(j.Qual(egSupervisor, "Register").Call(j.Op("&").Qual(path, r).Values()))
		appendCode(j.Qual(egAPI, "RegisterObject").Call(j.Qual(path, apiName)).Line())
		appendCode(j.Line())
	}

	file.Add(DefFunc(&Func{
		Name:  "init",
		Block: codes,
	}))
}
