apisix:
  node_listen: 9080
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    admin_listen:
      ip: 0.0.0.0
      port: 9180

    allow_admin:
      - 0.0.0.0/0

    admin_key:
      - name: "admin"
        key: iamadmin
        role: admin               

      - name: "viewer"
        key: iamviewer
        role: viewer

  etcd:
    host:                                      
      - "http://host.docker.internal:5379"     
    prefix: "/apisix"                        
    timeout: 30                            

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
