kind: HTTPServer
name: benchmark-ai-gateway-server
port: 8080
https: false
http3: false
keepAlive: true
keepAliveTimeout: 75s
maxConnection: 10240
cacheSize: 0
rules:
  - paths:
    - pathPrefix: /
      backend: benchmark-ai-gateway-pipeline

--- 

kind: AIGatewayController
name: AIGatewayController
providers:
- name: mock-openai
  providerType: openai
  baseURL: http://host.docker.internal:19999
  apiKey: empty

---

name: benchmark-ai-gateway-pipeline
kind: Pipeline
flow:
  - filter: ai-gateway-proxy

filters:
  - name: ai-gateway-proxy
    kind: AIGatewayProxy
    providerName: mock-openai
