service:
  # nodePort for easegress service
  nodePort: 30080
  # nodeport for egctl access
  adminPort: 31255

# image for easegress deployment
image:
  repository: megaease/easegress
  tag: latest

ingressClass:
  name: easegress

controller:
  name: easegress-ingress-controller
  # kubeConfig: # path to kube-config file
  # masterURL: # url to kube-api-server
  namespaces:
  - default

# numbers of Easegress IngressController replicas to install.
replicas: 1
