name: Integration-test

# Only trigger, when the test workflow succeeded
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  httpserver_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.5

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Test
        shell: bash
        run: |
          make httpserver_test
