name: TestPipeline

on:
  push:
    branches:
      - pipeline 
    paths:
      - "**/*.go"
      - "**/*.yaml"
      - "**/*.sh"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - pipeline 
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"

env:
  GO_VERSION: 1.17

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] 
    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Test
        shell: bash
        run: |
          make test TEST_FLAGS="-race -coverprofile=coverage.txt -covermode=atomic"

      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt
